[package]
name = "models"
version.workspace = true
edition.workspace = true

[dependencies]
regex = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", optional = true }

[features]
serde = ["dep:serde"]
