[package]
name = "sshinto"
version.workspace = true
edition.workspace = true

[dependencies]
lib_sshinto = { path = "../lib_sshinto" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
